### ISSUE TITLE
glibc 2.31

### ISSUE THREAD

**Issue by dfroger** [pdobsan/mailctl#10]
Hi,

I would like to use mailctl for [offlineimap+Gmail+OAuth2]( https://wiki.archlinux.org/title/OfflineIMAP#Configuring_OAuth2_and_getting_access_tokens_via_mailctl), because "less secure application" are blocked by Gmail since the 30 May, 2022.

I'm on `Linux Mint 20.3 Una`, which has glibc 2.31, which is incompatible with [mailctl-0.7.1-Linux-x86_64](https://github.com/pdobsan/mailctl/releases/download/0.7.1/mailctl-0.7.1-Linux-x86_64).

I tried to compile from source but got error which I didn't tried to solve.

What would you recommend? I'll try with an older release. Thanks!

**Comment by dfroger** [comment]
0.5.3 works with glibc 2.31.

But actually I will not use OAuth2. I just activated 2 factor auth + application password in Gmail, and setting `remotuser=xxx@gmail.com` and `remotepass=the-16-letter-app-password` in `~/.offlineimaprc` works.

**Comment by pdobsan** [comment]
First, I don't recommend to use older releases.

The current release compiles either with ghc 8.10.7 or 9.2.4.

Compiling from source might be easier than it seems. What ghc version did you use? What was the error?

Meanwhile your second message popped up. My guess is your "2 factors auth + application password " solution won't work for long. Google is really pushing ouath2.

**Comment by dfroger** [comment]
Thanks for the reply! So it's worth going to OAuth2.

I think my `cabal` is too old? Will try to updated it.

```bash
$ cabal --version
cabal-install version 2.4.0.0
compiled using version 2.4.0.1 of the Cabal library 
```

```bash
$ cabal update
Warning: The update command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-update command
or the legacy v1-update alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal update --index-state='2022-08-24T19:21:16Z'
```
```bash
$ cabal install
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Warning: mailctl.cabal:44:23:
unexpected end of input
expecting white space or "\""

MailCtl.Authorization,
MailCtl.CommandLine,
MailCtl.Environment,
MailCtl.Utilities,
Warning: mailctl.cabal:0:0: Unsupported cabal-version. See
https://github.com/haskell/cabal/issues/4899.
cabal: Failed parsing "./mailctl.cabal".
```

**Comment by dfroger** [comment]
```bash
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
```

**Comment by pdobsan** [comment]
These are old. Forget what the your OS provides.

Install a recent haskell tool chain for yourself using [ghcup](https://www.haskell.org/ghcup/). 

It should go something like this:

- install ghcup
- run `ghcup tui` to install ghc and cabal:
  - install `ghc 9.2.4` if that is an option otherwise `ghc 8.10.7`
  - install `cabal 3.6.2.0`
- then just try to compile `mailctl` from source

That installs `mailctl` into '~/.cabal/bin',

    git clone https://github.com/pdobsan/mailctl.git
    cd mailctl
    cabal update
    cabal install --install-method=copy

**Comment by dfroger** [comment]
I installed ghcup and it was compiling... It just ended! (ghcup works very nice)

```bash
$ /home/dfroger/.cabal/bin/mailctl --version
mailctl version 0.7.1
Copyright (C) Peter Dobsan 2022
```

Now, Gmail and offlineimap configuration... Thanks a lot for the help
