### ISSUE TITLE
Create and maintain wiki pages

### ISSUE THREAD

**Issue by pdobsan** [pdobsan/mailctl#13]
**Objective:** Create and maintain wiki pages containing additional information on using `mailctl`, in particular, specific instructions to various service providers. These pages should serve as a depository of the collective wisdom of using `mailctl` with various accounts.

Experience has shown that setting up email accounts for using OAuth2 and configure and use `mailctl` can be complicated. While many issues were raised and solved (more or less) after some fiddling the information gained during these sessions is scatted over in several issue and pull request threads, like #5, #11 and #12.

To remedy this situation I have set a wiki up with a few skeleton pages. I thought that collecting and maintaining such information  just in the Readme file could become quickly problematic so decided to go with the wiki.

**I'd very much welcome pull requests to this wiki!**

You can clone this wiki by the following command:

    git clone https://github.com/pdobsan/mailctl.wiki.git

**Comment by nicodebo** [comment]
Hello @pdobsan ,
I tried to improve the wiki documentation on using mailctl with a personal gmail account.
You can see the doc here https://github.com/nicodebo/mailctl_wiki/tree/feature/improve_wiki

**Comment by pdobsan** [comment]
@nicodebo,

That is great, exactly the kind of information I was hoping for.

I lifted the restriction on write access to the wiki, so now you can edit it directly.
Please do so!

Thank you

**Comment by nicodebo** [comment]
done, thank you.

**Comment by pdobsan** [comment]
not much activity on wiki pages, I close it down.
