### ISSUE TITLE
The official binary fails if the glib version is not 2.34

### ISSUE THREAD

**Issue by DidierSpaier** [pdobsan/mailctl#15]
Here (Slint 15.0):

./mailctl-0.7.4-Linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./mailctl-0.7.4-Linux-x86_64)
	linux-vdso.so.1 (0x00007ffd62164000)
	libm.so.6 => /lib64/libm.so.6 (0x00007febeaa8e000)
	libz.so.1 => /lib64/libz.so.1 (0x00007febeaa74000)
	libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007febea9fb000)
	libc.so.6 => /lib64/libc.so.6 (0x00007febea81c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007febeac08000)

But glibc 2.33 is shipped in Slint 15.0. What can be done? Is a previous version using glibc-2.33?

Cheers,
Didier

PS After having posted I have seen: https://github.com/pdobsan/mailctl/issues/10
But as a distribution maintainer I would prefer shipping a repackaged official binary, as I already do for pandoc.

**Comment by pdobsan** [comment]
> PS After having posted I have seen: #10 But as a distribution maintainer I would prefer shipping a repackaged official binary, as I already do for pandoc.

I cannot offer any better solution than what I suggested in #10, that is build from source.
That worked well,

**Comment by DidierSpaier** [comment]
Thanks for your fast answer anyway.
