### ISSUE TITLE
Support request: "Token has been expired or revoked."

### ISSUE THREAD

**Issue by the-isz** [pdobsan/mailctl#17]
Hi mailctl team!

I'm using mailctl with offlineimap and msmtp. Everything works as expected after `mailctl authorize`, i.e. I can receive mail from my google account via offlineimap and send mails via msmtp.

However, it only works for a short while (I haven't figured out the exact period yet, but at least until the next reboot). Then, mailctl complains that the token isn't valid anymore:

```
# mailctl access mygoogleaddress@gmail.com
{
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
mailctl: getEmailAuth:
fetchAuthRecord: Error in $: parsing MailCtl.Environment.AuthRecord(AuthRecord) failed, key "access_token" not found
CallStack (from HasCallStack):
  error, called at lib/MailCtl/Authorization.hs:101:22 in mailctl-0.7.4-ff681da555a2803c4a4890fc84e92bdcf7e0808c80f51bdad52a4173c2c12c04:MailCtl.Authorization
```

```
# mailctl renew mygoogleaddress@gmail.com
{
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
mailctl: fetchAuthRecord: Error in $: parsing MailCtl.Environment.AuthRecord(AuthRecord) failed, key "access_token" not found
CallStack (from HasCallStack):
  error, called at lib/MailCtl/Authorization.hs:232:19 in mailctl-0.7.4-ff681da555a2803c4a4890fc84e92bdcf7e0808c80f51bdad52a4173c2c12c04:MailCtl.Authorization
```

Going through the `mailctl authorize` process another time fixes the issue for a while.

I have written my own tool to store and load credentials replacing gpg, so I can see multiple reasons for the error above:

1. My tool doesn't load the credentials correctly (although my tests indicate otherwise)
2. I have somehow misconfigured the GMail API and the tokens decay sooner than expected
3. I misunderstood something about mailctl/the token process completely

From the error output above, can you deduce what the issue is, i.e. in which direction I need to investigate?

Thanks in advance!

**Comment by pdobsan** [comment]
On Fri, Nov 25, 2022 at 06:43:33AM -0800, the-isz wrote:
> # mailctl access ***@***.***
> {
>   "error": "invalid_grant",
>   "error_description": "Token has been expired or revoked."
> }
> ```
> # mailctl renew ***@***.***
> {
>   "error": "invalid_grant",
>   "error_description": "Token has been expired or revoked."
> }

> Going through the `mailctl authorize` process another time fixes the issue for a while.

> 2. I have somehow misconfigured the GMail API and the tokens decay sooner than expected

Close enough. I suspect that the `client_id/client_secret` in your
`services.yaml` were obtained from google as developer credentials. These are
temporary (just for the development) and expire in a week or so. You need to
properly register your application with google in a rather cumbersome
process to get permanent credentials.

Most people don't bother, they just use the credentials of a registered
open source (email) application. (It is not too difficult to find them.)

**Comment by the-isz** [comment]
Hi @pdobsan,

thank you very much for your helpful comment! You are correct and I created my own credentials as described in offlineimap's guide. Unfortunately, they failed to mention that these credentials would be temporary :(

I haven't found the credentials you hinted at yet, but I'm pretty sure I know which application you mean and should be able to find them eventually.

During my research, I found the alternative of using an application-specific password via 2-step verification. This seems a whole lot easier than the burning OAuth2 loops a simple user like me has to jump though `XD

But before I go that way: Do you see a reason to prefer OAuth2? Apart from me not using your great application, of course.

**Comment by ferdinandyb** [comment]
I want to test this at some point, but it seems to me that you can publish your google app without costs and security checks as long as you don't mind the ugly warning that your application has not been scrutinized yet. At least I'm using such an app for reading my calendar, but I didn't specifically test that for email (yet).

**Comment by pdobsan** [comment]
On Tue, Nov 29, 2022 at 02:24:50PM -0800, Bence Ferdinandy wrote:
> I want to test this at some point, but it seems to me that you can
> publish your google app without costs and security checks as long as
> you don't mind the ugly warning that your application has not been
> scrutinized yet.

That could be great, depending how/when this warning manifests itself.

If you figure this out please put the steps of creating *permanent*
client_id/client_secret for google into mailctl's wiki.

**Comment by the-isz** [comment]
Well, until I find a reason not to, I'll stick with the application-specific password that google allows. It's just so much more easy to set up.

Thanks for your support; I'll close this ticket now.

**Comment by ferdinandyb** [comment]
Ok, so actually it was more painless to test then I anticipated. You don't even need to enable the gmail api, the authorization asked for by mailctl seems to be enough. You are greeted with this warning screen before allowing you to authorize though:

![image](https://user-images.githubusercontent.com/6343487/205755288-4b5e182d-3758-4efc-b0da-656bd1a04708.png)

Now I need to wait at least a week to see if the token expires or not.

**Comment by ferdinandyb** [comment]
It also seems to work for company-gmail addresses, although I suspect company policy could limit which clients are allowed (my Uni does that with outlook on o365).

**Comment by ferdinandyb** [comment]
I have no been running this setup for 2 weeks, so I think we can safely conclude it works.
