### ISSUE TITLE
Hardcoded default config value

### ISSUE THREAD

**Issue by JohnyZ89** [pdobsan/mailctl#2]
Hello. Could you change source code to use XDG_CONFIG_HOME variable as default instead of hardcoded home directory for user peter ?

https://github.com/pdobsan/mailctl/blob/fa5eae4180af67cba022716ef5cda98ce087c791/lib/MailCtl/CommandLine.hs#L40

**Comment by pdobsan** [comment]
On Thu, Jun 30, 2022 at 12:20:26AM -0700, JohnyZ89 wrote:
> Hello. Could you change source code to use XDG_CONFIG_HOME variable as
> default instead of hardcoded home directory for user peter ?

Oops!
Fixed it, the default config file now is `$XDG_CONFIG_HOME/mailctl/config.yaml`
See release 0.5.3
