### ISSUE TITLE
Unable to build mailctl: Module ‘Network.HTTP2.Frame’ does not export ‘HTTP2Error(..)’

### ISSUE THREAD

**Issue by mm-cms** [pdobsan/mailctl#20]
When trying to build `mailctl` with Docker using `haskell:9.4-slim-buster` as base image and following the instructions in the README, following error occurs (end of log output of `cabal install --install-method=copy --verbose`):

```
[1 of 3] Compiling Web.Twain.Types  ( src/Web/Twain/Types.hs, dist/build/Web/Twain/Types.o, dist/build/Web/Twain/Types.dyn_o )
[2 of 3] Compiling Web.Twain.Internal ( src/Web/Twain/Internal.hs, dist/build/Web/Twain/Internal.o, dist/build/Web/Twain/Internal.dyn_o )

src/Web/Twain/Internal.hs:19:47: error:
    Module ‘Network.HTTP2.Frame’ does not export ‘HTTP2Error(..)’
   |
19 | import Network.HTTP2.Frame (ErrorCodeId (..), HTTP2Error (..))
   |                                               ^^^^^^^^^^^^^^^
CallStack (from HasCallStack):
  withMetadata, called at src/Distribution/Simple/Utils.hs:370:14 in Cabal-3.8.1.0-inplace:Distribution.Simple.Utils
Error: cabal: Failed to build mailctl-0.8.0 because it depends on
mailctl-0.8.0 which itself failed to build.
Failed to build mailctl-0.8.0 because it depends on mailctl-0.8.0 which itself
failed to build.
Failed to build
twain-2.1.0.0-0c26f962d7c7d1f7a4f635d9e6183de72f02bda4f286d6b77707f8b31fee21ca.
```

A short investigation shows that "Network.HTTP2 and Network.HTTP2.Priority are removed" and "HTTP2Error is redefined" according to the [`http2` changelog for version 4.0.0](https://github.com/kazu-yamamoto/http2/blob/136188cdf4c2d750f3f8ac780a7be4b33b36d12d/ChangeLog.md#400).

The output of `cabal-plan` seems to indicate that http2-4.0.0 seems to be pulled by `twain-2.1.0.0` which is a direct dependency of ` mailctl`:
```
 ├─ mailctl-0.8.0
...
 │   ├─ twain-2.1.0.0
 │   │   ├─ aeson-2.1.1.0 ┄┄
 │   │   ├─ base-4.17.0.0 ┄┄
 │   │   ├─ bytestring-0.11.3.1 ┄┄
 │   │   ├─ case-insensitive-1.2.1.0 ┄┄
 │   │   ├─ cookie-0.4.6 ┄┄
 │   │   ├─ either-5.0.2
 │   │   │   ├─ base-4.17.0.0 ┄┄
 │   │   │   ├─ bifunctors-5.5.14 ┄┄
 │   │   │   ├─ mtl-2.2.2 ┄┄
 │   │   │   ├─ profunctors-5.6.2
 │   │   │   │   ├─ base-4.17.0.0 ┄┄
 │   │   │   │   ├─ base-orphans-0.8.7 ┄┄
 │   │   │   │   ├─ bifunctors-5.5.14 ┄┄
 │   │   │   │   ├─ comonad-5.0.8 ┄┄
 │   │   │   │   ├─ contravariant-1.5.5 ┄┄
 │   │   │   │   ├─ distributive-0.6.2.1 ┄┄
 │   │   │   │   ├─ tagged-0.8.6.1 ┄┄
 │   │   │   │   └─ transformers-0.5.6.2 ┄┄
 │   │   │   └─ semigroupoids-5.3.7 ┄┄
 │   │   ├─ exceptions-0.10.5 ┄┄
 │   │   ├─ http-types-0.12.3 ┄┄
 │   │   ├─ http2-4.0.0
```

This seems to be an upstream issue with `twain`, but its .cabal file seems to indicate that [`http2` seems to be pinned to version < 3.3.0](https://github.com/alexmingoia/twain/blob/e182906b8ef41f4d7310e535dcc21ce718990065/twain.cabal#L47).

I've almost no experience in Haskell, therefore I don't know what causes this issue and how it can be resolved.

**Comment by pdobsan** [comment]
On Thu, Feb 16, 2023 at 08:48:40AM -0800, martin-mueller-cemas wrote:
> This seems to be an upstream issue with `twain`, but its .cabal file
> seems to indicate that [`http2` seems to be pinned to version <
> 3.3.0](https://github.com/alexmingoia/twain/blob/e182906b8ef41f4d7310e535dcc21ce718990065/twain.cabal#L47).

You are right. I modified the cabal build process and now it works with
both ghc 9.2.6 and 9.4.4. I hope that also solves your problem on
docker.

I have made a new release, was long time due anyway.

Please note that I am moving away from github to sourcehut although this
repo will be kept mirrored here on github too. You can grab the source
from either places, or the releases from sourcehut:

    https://git.sr.ht/~petrus/mailctl/refs
