### ISSUE TITLE
Github release broken

### ISSUE THREAD

**Issue by Croissong** [pdobsan/mailctl#21]
Hey!
After 1c25b8a the latest Github release ([0.7.4](https://github.com/pdobsan/mailctl/releases/tag/0.7.4)) & its asset downloads seem to be broken.
Interestingly https://api.github.com/repos/pdobsan/mailctl/releases/latest still shows `0.7.4` as the latest release, while https://api.github.com/repos/pdobsan/mailctl/releases does not list it anymore.

It would be great if you could create a new Github release for `0.8.3` - ideally again with prebuilt executable assets :)

**Comment by Croissong** [comment]
Sorry, I just now read https://github.com/pdobsan/mailctl#compiled-static-binaries.

Sourcehut release would of course work as well.
However I can't seem to find the 
>  tar file containing the compiled executable from that page.
https://git.sr.ht/~petrus/mailctl/archive/0.8.3.tar.gz does not contain one, right?

Other than that, maybe the existing Github releases could be fully removed if possible, to avoid confusion.

**Comment by pdobsan** [comment]
On Tue, Feb 21, 2023 at 08:43:14AM -0800, Jan Möller wrote:
> After 1c25b8a the latest Github release (`0.7.4`) & its asset downloads seem to be broken.

I am in the process of migrating to sourcehut, and keep the github repo just
as a mirror. I hope the troubles are just temporary.

The link you used at sourcehut is the repo's content at the given tag. To
get to the compiled assets attached to the release you need to click on the
release number and select this link to download:

    https://git.sr.ht/~petrus/mailctl/refs/download/0.8.3/mailctl-0.8.3.tgz

The new AUR bin package will also come soon.

Sorry about the confusion, it's hard to perform this migration as an atomic
operation.

Followups: send an email to ***@***.***
or report bugs by sending email to ***@***.***

**Comment by Croissong** [comment]
> To get to the compiled assets attached to the release you need to click on the release number and select this link to download.

Omg, I can't believe I missed that...
Thanks for the hint :+1:
