### ISSUE TITLE
No support for multiple corporate gmail addresses

### ISSUE THREAD

**Issue by hseg** [pdobsan/mailctl#22]
While passing `dummy-email-address` to `mailctl authorize --company` does make the authorization logic go through,
it both overwrites whatever other corporate email was previously set up, and makes the token only identifiable as `dummy-email-address`

**Comment by hseg** [comment]
Indeed, `--company` might as well be called `--nohint` -- that's what it's actually doing, giving the authorization page a dummy login hint to force it to open the account picker

**Comment by pdobsan** [comment]
On Tue, Sep 26, 2023 at 12:26:23PM -0700, hseg wrote:
> Indeed, `--company` might as well be called `--nohint` -- that's what it's
> actually doing, giving the authorization page a dummy login hint to force
> it to open the account picker

What happens if instead of giving a dummy the program does not send a
`login_hint` parameter at all? Would that also open the account picker?

I don't have access to a corporate account so cannot try.

**Comment by hseg** [comment]
Appears so, under google.
BTW, don't know why but without suppressing the hint, am getting HTTP 400 responses when trying to use a corporate account.
