### ISSUE TITLE
CAS redirect not working

### ISSUE THREAD

**Issue by b1noc** [pdobsan/mailctl#3]
Ok this might be a tough one.
I'm trying to login to my University managed Gmail account (which is ambitious I know).
Using the google template I get to the university login page on http://localhost:8080/start just fine (using thunderbirds `client_id` and `client_secret`).
But when I click the Login Button it redirects me to

`http://localhost:8080/cas/login?service=https%3A%2F%2Fidp.ltu.se%2Fidp%2FAuthn%2FExternal%3Fconversation%3De1s1%26entityId%3Dgoogle.com`

And I get the `Not found...` Message.
If I decode the service url and plug it into my browser the url seems to be fine. I get a wrong session error obviously but it's not a dead end.

I'm not quite sure if there is other Information I could provide so just let me know if you need anything else.

**Comment by b1noc** [comment]
Ok so I did not think thoroughly enough. Of course I have to change that redirect uri. I did that and now I am redirected to a page that tells me that I signed up successfully and that I'm connected to the central CAS but the mailctl still hangs at the dialogue without creating a `.auth` file like it did with the regular google login.

**Comment by pdobsan** [comment]
> Ok this might be a tough one. I'm trying to login to my University managed Gmail account (which is ambitious I know).

Yeah, that is ambitious, but your experimentation has given me some clue, so ...

Just to be on the same page make sure you are always using the most recent version, at the moment of writing it is 0.5.3, but can change any time.  The config file now defaults to `$XDG_CONFIG_HOME/mailctl/config.yaml`.

>  I'm thinking that maybe my `client_id` and `client_secret` don't work but I'm not sure this is related to the process missing its session.

No they should be fine. Also stick to the original `redirect_uri: http://localhost:8080`.
I need some time to think how to manage the second redirection without losing session.

If any time you manage to create an `.auth` file, ignore the other errors, try to use it:

    mailctl access <email>

if that fails, try to decrypt it to see its content:

    gpg --decrypt ~/.local/var/mailctl/<email>.auth

**Comment by pdobsan** [comment]
Release 0.6.1 tries to deal with the CAS server related redirection. Let me know if how that works out for your case.

**Comment by b1noc** [comment]
Sorry for my late reply, and thanks for all the work. I'll try it next week.

**Comment by ferdinandyb** [comment]
@b1noc how did you get Thunderbird's client_id and secret? I'm struggling with a similar issue (Uni on office365 #5 ) and I think that would solve my problem.

**Comment by ferdinandyb** [comment]
Nevermind, I found it [here](https://hg.mozilla.org/comm-central/file/tip/mailnews/base/src/OAuth2Providers.jsm).

**Comment by b1noc** [comment]
Thanks for all the work. It works perfectly now.
I'm sorry I never responded. I had to hand in my thesis and my time management and everything else went over board.
