### ISSUE TITLE
How often do I need to run renew?

### ISSUE THREAD

**Issue by ferdinandyb** [pdobsan/mailctl#7]
So while trying to dig around and solve the MS login issue, I realized that the tokens I'm getting from google expire in an hour (although I'm 99% sure, that I actually managed to use the to get email way later than an hour ...). I also noticed `mailctl` has a renew command and something about `cron` but only related to `fdm` (which I don't use) if I understand correctly. 

My understanding of oauth2 is pretty limited, so maybe this sounds like a very obvious question, but: do I need to set up regular calls to `mailctl renew`? If yes, how often to not have to worry about having to authorize again? And if yes, I'd also like to put out a feature request for a `mailctl renew --all` or something along those lines.

Thanks!

**Comment by pdobsan** [comment]
> My understanding of oauth2 is pretty limited, so maybe this sounds like a very obvious question, but: do I need to set up regular calls to `mailctl renew`? 

No, you don't. "access token renewal happens automatically in the background transparent to the user." (quote from the readme.) That is the whole point of `mailctl`.  You just call whatever you call for sending/receiving email. The `renew` command is there mainly for testing purposes, it just bypasses checking the age of the `access_token` and gets a new one regardless.

And regarding `authorize` you need to call it only once at the beginning to obtain the so called `refresh_token` which is used in the renewal process. Have a look at the contents of your `.auth` file and/or the syslog of `mailctl`. That might help your understanding what is going on.

If you lose your `refresh_token`, or our service provider overlords stop accepting for whatever reason then and only then you need to `authorize` again.  I have not seen this to happen in several months of use.

**Comment by ferdinandyb** [comment]
Oh, okay, thanks, I checked the `auth` file and did some reading so now it's a bit more clear, although I did end up asking a question on stackoverflow :D Anyway, I'll close this issue, thanks again!
