### ISSUE TITLE
`Something went wrong` in localhost `fetchAuthRecord: Error in $: Failed reading: not a valid json value`

### ISSUE THREAD

**Issue by CosmosAtlas** [pdobsan/mailctl#8]
I get an error after successfully login the microsoft account.

The webpage will display the text "Something went wrong"

And in the terminal it prints out a bunch of html source code with the following error

```
... Omitted full HTML source code
function(){document.cookie=n.name+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;"},e.$Do.when("doc.load",function(){
setTimeout(M,L),setTimeout(S,0)}))}}(window,document,$Prefetch);

;
})();
//]]>
</script>

</body>
</html>
localWebServer:
fetchAuthRecord: Error in $: Failed reading: not a valid json value
CallStack (from HasCallStack):
  error, called at lib/MailCtl/Authorization.hs:278:17 in mailctl-0.6.4-f4efc9a3e27c412daaa05fd4c22ce22b7d21cf8b50d56ab76f3bc63a27ae8204:MailCtl.Authorization

```

**Comment by pdobsan** [comment]
I don't have a microsoft account so I rely on users' feedback. Some people manage to obtain the authorization others don't. So far I could not pinpoint what the issue is.

You might want to attach your config files to your issue, and specify how you exactly run the program.

**Comment by CosmosAtlas** [comment]
I was able to set up OAuth with the oauth script provided by mutt. Also, it was mainly hit or miss, 3 options were provided, I tried two of them, one worked, one didn't. 

Closing since unable to provide more information.
